import type { Metadata } from "next";
import "./globals.css";
import SideNav from '@/app/ui/sidenav';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen flex-col lg:flex-row lg:overflow-hidden bg-gray-900">
          <div className="w-full flex-none lg:w-64">
            <SideNav />
          </div>
          <div className="flex-grow p-6 lg:overflow-y-auto lg:p-12">{children}</div>
        </div>
      </body>
    </html>
  );
}
